### PR TITLE
Separator between options is | instead of space

### PR DESCRIPTION
**Pull request by NhanAZ**

### CODE REVIEW

**Review by tgwaste — COMMENTED** [review]
| is typically use in a usage statement to mean "OR".  Space would not be appropriate here.

**Comment by NhanAZ** [comment]
This PR is made by me based on some trusted code like:
- https://github.com/dktapps-pm-pl/pmforms-demo/blob/master/plugin.yml#L12
- https://github.com/poggit-orphanage/EconomyS/blob/master/EconomyAuction/plugin.yml#L11
- https://github.com/PMPLS/simple-plugins/blob/master/SimplePermissions/plugin.yml#L9
- https://github.com/poggit-orphanage/EconomyS/blob/master/EconomyCasino/plugin.yml#L40
- https://github.com/poggit-orphanage/EconomyS/blob/master/EconomySell/plugin.yml#L12

Anyway. Thanks for reviewing the pull request. Wish you a good day.

**Comment by tgwaste** [comment]
Sorry, my bad I read it wrong.

**Comment by NhanAZ** [comment]
No problem. Good thing it was merged!

**Pull request merged**
